#' @title Add information to TDA dataframe
#'
#' @description This function computes the average value of the features
#' and the size of each rows of the dataframe
#' generated by the \code{\link{mapperCore}} function.
#'
#' @param dfMapper A data.frame generated by the \code{\link{mapperCore}}
#' function.
#' @param df A data.frame with scaled vslues (\code{\link{importSplitScale}})
#' in the classical n) x m form: rows (n) and columns (m) must be observations
#' and features, respectively.
#'
#' @return A data.frame with the average value and the size.
#'
#' @author Laura Ballarini, Mattia Chiesa
#'
#' @examples
#' ## use example data:
#' data(dfMapper_tda)
#' data(df_test_proj)
#' enrich_mat_tda <- tdaDfEnrichment(dfMapper_tda, df_test_proj)
#'
#' @seealso
#' \code{\link{importSplitScale}},
#' \code{\link{dfToDistance}},
#' \code{\link{dfToProjection}},
#' \code{\link{mapperCore}},
#' \code{\link{jaccardMatrix}}
#'
#' @export
#'
tdaDfEnrichment <- function(dfMapper, df){

  # checks----------------------------------------------------------------------
  # check missing arguments
  if (missing(dfMapper))
    stop("'dfMapper' argument must be provided")

  if (missing(df))
    stop("'df' argument must be provided")

  # check the type of argument
  if (!is.data.frame(dfMapper))
    stop("'dfMapper' argument must be a data.frame")

  if (!is.data.frame(df))
    stop("'df' argument must be a data.frame")

  # specific checks
  if (dim(dfMapper)[2] != 1)
    stop("dim(dfMapper)[2] must be equal to 1")

  if (!all(vapply(dfMapper, class, FUN.VALUE=character(1)) %in% "character"))
    stop("'dfMapper' elements must be of type 'character'")

  if (dim(df)[1] < 10)
    stop("n. of 'df' rows must greater than 10")

  if (dim(df)[2] < 2)
    stop("n. of 'df' columns must be greater than 2")

  if (!all(vapply(df, class, FUN.VALUE=character(1)) %in%
                                                     c("numeric", "integer")))
    stop("'df' variables must be all numeric")


  # check the presence of NA or Inf
  if (any(is.na(dfMapper)))
    stop("NA values are not allowed in the 'dfMapper' data.frame")

  if (any(is.infinite(as.matrix(dfMapper))))
    stop("Inf values are not allowed in the 'dfMapper' data.frame")

  if (any(is.na(df)))
    stop("NA values are not allowed in the 'df' data.frame")

  if (any(is.infinite(as.matrix(df))))
    stop("Inf values are not allowed in the 'df' data.frame")

  # body------------------------------------------------------------------------
  dbDataRes <- matrix(nrow = nrow(dfMapper),ncol=ncol(df))
  colnames(dbDataRes) <- colnames(df)
  rownames(dbDataRes) <- rownames(dfMapper)

  nodeSize <- c()
  for (i in seq_len(nrow(dfMapper))) {
    listaSample <- unlist(strsplit(dfMapper[i,1]," "))
    # compute the means for each variable
    vectorMeans <- round(colMeans(df[listaSample, ],na.rm = TRUE),3)
    dbDataRes[i,] <- vectorMeans
    nodeSize[i] <- length(listaSample)
  }
  dbDataRes <- as.data.frame(dbDataRes)
  # add a column with the number of examples for each node
  dbDataRes$size <- nodeSize

  return(dbDataRes)
}
